eureka:
  client:
    serviceUrl:
      defaultZone:  http://10.100.2.106:9001/eureka/
  instance:
    prefer-ip-address: true

spring:
  session.store-type: none
  redis:
    host: 10.100.2.106
    port: 6379
    pool.max-active: 8

  cloud:
    config:
      server:
        native:
          searchLocations: file:/root/xcmg/conf
    inetutils:
      preferredNetworks[0]: ^10\.100

  profiles:
    active: native


  http:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

  file:
    download:
      path: /root/xcmg/file/

  zipkin:
    enabled: false

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/root/xcmg
fast:
  auth:
    login:
      url: /ius/auth/login,/ius/auth/sigin
    logout:
      url: /ius/auth/logout,/ius/auth/signout
    webfront:
      path: /root/xcmg
    user:
      session:
        ttl: 3600

zuul:
  routes:
    api-a.path: /ius/**
    api-a.serviceId: fast-auth-server

    api-c.path: /dev/**
    api-c.serviceId: device-service

  host:
    socket-timeout-millis: 6000000
    connect-timeout-millis: 6000000

  sensitive-headers: x-user-id,x-access-client,x-case-ticket
  ignored-patterns: /**/fast-amigo/**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000000

ribbon:
  ReadTimeout: 6000000
  ConnectTimeout: 6000000

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  dialect: oracle
downloadName: /opt/service/ftp/test.txt

logging:
  file: /opt/xgbj/service/mylogfile.log  #日志路径
  level.root: info
  log.level: debug

jco:
  client:
    user: DMS_QC
    passwd: 123456
    lang: ZH
    client: 800
    sysnr: 00
    ashost: 10.1.1.31

server:
  session:
    cookie.max-age: 7200
