eureka:
  client:
    service-url:
      defaultZone: http://eureka.jt.com:9000/eureka/
    fetchRegistry: true
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
server:
  port: 18005

fast:
  webfront:
    path: /root/jt_prop/dist
    error-page:
      notfound: /index.html

spring:
  redis:
    host: redis.jt.com
    port: 6379
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${fast.webfront.path}
  #  cloud:
  #    inetutils:
  #      preferred-networks:
  #      - 127.0
  zipkin:
    enabled: false
    #当enabled=true时，base-url需要配置
    base-url: http://192.168.1.149:9002

zuul:
  routes:
    api-a:
      path: /cop/** 
      service-id: copper-purchase 
    api-b:
      path: /cos/** 
      service-id: copper-server 
    api-c:
      path: /jcs/** 
      service-id: storage-server 
    api-d:
      path: /ius/** 
      service-id: fast-auth-server  
    api-e:
      path: /web/** 
      service-id: copper-surface
    api-f:
      path: /ss/** 
      service-id: storage-server
    api-g:
        path: /ss-cdw/**
        service-id: storage-server-cdw
cas:
  feign:
    name: ljy-nju-charging-service
  auth:
    ticket-key: ticket
  defaultUrl: http://219.219.116.11:8080
logging:
  file: logs/gateway.log
  level:
    root: info
    ufast: info
